### ISSUE TITLE
Galleries的页面不能显示具体的相册

### ISSUE THREAD

**Issue by MeiZia** [izhaoo/hexo-theme-zhaoo#31]
作者你好，我按照教程上面设置galleries的方法进行配置，但是最终每一个相册还是没有显示出来。
在使用hexo g命令的时候，有如下的报错：

ERROR { TypeError: /Users/meizi/web-blog/themes/zhaoo/layout/gallery.ejs:1
 >> 1| <% var galleries = [];
    2| 
    3| if (site.data && site.data.galleries) {
    4|   galleries = site.data.galleries;}

Cannot read property 'photos' of undefined
    at eval (/Users/meizi/web-blog/themes/zhaoo/layout/gallery.ejs:24:29)
    at gallery (/Users/meizi/web-blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled.locals [as _compiled] (/Users/meizi/web-blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/meizi/web-blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/meizi/web-blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/meizi/web-blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/meizi/web-blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/meizi/web-blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:907:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  path: '/Users/meizi/web-blog/themes/zhaoo/layout/gallery.ejs' }

麻烦帮忙看一下，谢谢啦！

**Comment by izhaoo** [comment]
方便的话加我QQ吧，894519210.

**Comment by izhaoo** [comment]
目录 `_data` 需要加一个下划线，别忘了哦~
